# .github/workflows/deploy.yml
name: Build and Push Docker to GCP

on:
  push:
    branches:
      - main   # dispara quando houver push na branch main

env:
  GCP_PROJECT: ${{ vars.GCP_PROJECT }}
  REPO_NAME: ${{ vars.ARTIFACT_REGISTRY_REPO_ONLINE_RESUME }}
  IMAGE_NAME: ${{ vars.ARTIFACT_REGISTRY_IMAGE_ONLINE_RESUME }}
  REGION: us-central1

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Configure Docker for GCP
        run: gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev

      - name: Build and Push Docker image
        run: |
          DOCKER_IMAGE="${{ env.REGION }}-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.REPO_NAME }}/${{ env.IMAGE_NAME }}"
          docker build -t $DOCKER_IMAGE:${GITHUB_SHA} .
          docker push $DOCKER_IMAGE:${GITHUB_SHA}