# .github/workflows/deploy.yml
name: Build and Push Docker to GCP

on:
  push:
    branches:
      - main   # dispara quando houver push na branch main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Pega o código do repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Configura GCP
      - name: Authenticate to GCP
        uses: google-github-actions/auth@v1
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      # 3️⃣ Configura Docker para usar o Artifact Registry
      - name: Configure Docker for GCP
        run: gcloud auth configure-docker us-central1-docker.pkg.dev

      # 4️⃣ Build da imagem Docker
      - name: Build Docker image
        run: docker build -t us-central1-docker.pkg.dev/web-development-485110/online-resume/resume:${GITHUB_SHA} .

      # 5️⃣ Push da imagem Docker para Artifact Registry
      - name: Push Docker image
        run: docker push us-central1-docker.pkg.dev/web-development-485110/online-resume/resume:${GITHUB_SHA}